config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'categories#index'

  resources :categories do
    resources :systems do
      resources :images do
        resources :notes
      end
    end
  end

  resources :pools
  resources :oses
  resources :users
  resources :clonezilla_versions
  resources :support_stuffs, only: [:index, :update]
  resources :autozilla_key_configs
  resources :sessions, only: [:index, :create, :edit, :update]
  resources :locations, only: [:index, :create, :update]

  # Easter egg :D
  get '/ohya!', to: 'randy#savage'

  # Setting up QA routes
  get '/applyQA', to: 'qa#applyQA'
  resources :keyfiles
  get '/qa', to: 'qa#qa'
  get '/view', to: 'qa#view'
  get '/qa_results', to: 'qa#index'
  post '/qa_results', to: 'qa#create'
  get '/qa_results/:id', to: 'qa#show', as: 'view_results'

  get '/autozilla_key', to: 'autozilla_key_configs#index'
  get '/autozilla_key/rebuild', to: 'autozilla_key_configs#rebuildKey'
  get '/autozilla_key/selfupdate', to: 'autozilla_key_configs#selfUpdate'
  get '/clonezilla_version/:id/newCZFiles', to: 'clonezilla_versions#populateCZFiles', as: 'populateCZ'

  # Switching status between enable and disable
  get '/clonezilla_version/:id/changeStatus', to: 'clonezilla_versions#changeStatus', as: 'changeCZStatus'
  get '/order_group/:id/changeStatus', to: 'pools#changeStatus', as: 'changePoolStatus'
  get '/operating_system/:id/changeStatus', to: 'oses#changeStatus', as: 'changeOSStatus'
  get '/locations/:id/changeStatus', to: 'locations#changeStatus', as: 'changeLocStatus'

  # Setting default
  get '/locations/:id/changeDefault', to: 'locations#changeDefault', as: 'changeLocDefault' 
  get '/clonezilla/:id/changeDefault', to: 'clonezilla_versions#changeDefault', as: 'changeCZDefault' 
end

app/models/search.rb
class Search < ApplicationRecord
  has_many :users
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index

    if params[:search]
      @categories = Category.search(params[:search]).order(:name)
      @systems = System.search(params[:search]).order(:name)
      @images = Image.search(params[:search]).order(:name)
    end

  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.erb
<% if @categories.present? %>
 <table class="table table-hover table-responsive table-striped">
    <thead>
      <td></td>
      <th>Name</th>
    </thead>
    <tbody>
      <% @categories.each do |cat| %>
        <tr data-link="<%=category_path(cat.id)%>">
          <td><%= link_to 'View', category_path(cat.id) %></td>
          <td><%= cat.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% else %>

  <p>No search found in categories.</p>
<% end %>

<% if @systems.present? %>
 <table class="table table-hover table-responsive table-striped">
    <thead>
      <td></td>
      <th>Name</th>
    </thead>
    <tbody>
      <% @systems.each do |sys| %>
        <tr data-link="<%=category_system_path(sys.category_id,sys.id)%>">
          <td><%= link_to 'View', category_system_path(sys.category_id, sys.id) %></td>
          <td><%= sys.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>

  <p>Found no systems for systems.</p>
<% end %>

<% if @images.present? %>
 <table class="table table-hover table-responsive table-striped">
    <thead>
      <td></td>
      <th>Name</th>
    </thead>
    <tbody>
      <% @images.each do |img| %>
        <tr data-link="<%= category_system_path(img.system.category_id, img.system, img.id)%>">
          <td><%= link_to 'Edit', category_system_path(img.system.category_id, img.system, img.id) %></td>
          <td><%= img.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>

  <p>Found nothing for search images</p>
<% end %>

app/views/searches/search.html.erb
<% if @categories.present? %>
 <table class="table table-hover table-responsive table-striped">
    <thead>
      <td></td>
      <th>Name</th>
    </thead>
    <tbody>
      <% @categories.each do |cat| %>
        <tr data-link="<%=category_path(cat.id)%>">
          <td><%= link_to 'View', category_path(cat.id) %></td>
          <td><%= cat.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% else %>

  <p>No search found in categories.</p>
<% end %>

<% if @systems.present? %>
 <table class="table table-hover table-responsive table-striped">
    <thead>
      <td></td>
      <th>Name</th>
    </thead>
    <tbody>
      <% @systems.each do |sys| %>
        <tr data-link="<%=category_system_path(sys.category_id,sys.id)%>">
          <td><%= link_to 'View', category_system_path(sys.category_id, sys.id) %></td>
          <td><%= sys.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>

  <p>Found no systems for systems.</p>
<% end %>

<% if @images.present? %>
 <table class="table table-hover table-responsive table-striped">
    <thead>
      <td></td>
      <th>Name</th>
    </thead>
    <tbody>
      <% @images.each do |img| %>
        <tr data-link="<%= category_system_path(img.system.category_id, img.system, img.id)%>">
          <td><%= link_to 'Edit', category_system_path(img.system.category_id, img.system, img.id) %></td>
          <td><%= img.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>

  <p>Found nothing for search images</p>
<% end %>